/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionSlugRouteImport } from './routes/section.$slug'
import { Route as ArticleSlugRouteImport } from './routes/article.$slug'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicCronIngestNewsRouteImport } from './routes/api/public/cron/ingest-news'
import { Route as ApiPublicCronIngestBreakingRouteImport } from './routes/api/public/cron/ingest-breaking'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionSlugRoute = SectionSlugRouteImport.update({
  id: '/section/$slug',
  path: '/section/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleSlugRoute = ArticleSlugRouteImport.update({
  id: '/article/$slug',
  path: '/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCronIngestNewsRoute = ApiPublicCronIngestNewsRouteImport.update({
  id: '/api/public/cron/ingest-news',
  path: '/api/public/cron/ingest-news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronIngestBreakingRoute =
  ApiPublicCronIngestBreakingRouteImport.update({
    id: '/api/public/cron/ingest-breaking',
    path: '/api/public/cron/ingest-breaking',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/section/$slug': typeof SectionSlugRoute
  '/api/public/cron/ingest-breaking': typeof ApiPublicCronIngestBreakingRoute
  '/api/public/cron/ingest-news': typeof ApiPublicCronIngestNewsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/section/$slug': typeof SectionSlugRoute
  '/api/public/cron/ingest-breaking': typeof ApiPublicCronIngestBreakingRoute
  '/api/public/cron/ingest-news': typeof ApiPublicCronIngestNewsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/search': typeof SearchRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/article/$slug': typeof ArticleSlugRoute
  '/section/$slug': typeof SectionSlugRoute
  '/api/public/cron/ingest-breaking': typeof ApiPublicCronIngestBreakingRoute
  '/api/public/cron/ingest-news': typeof ApiPublicCronIngestNewsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/search'
    | '/admin'
    | '/article/$slug'
    | '/section/$slug'
    | '/api/public/cron/ingest-breaking'
    | '/api/public/cron/ingest-news'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/search'
    | '/admin'
    | '/article/$slug'
    | '/section/$slug'
    | '/api/public/cron/ingest-breaking'
    | '/api/public/cron/ingest-news'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/search'
    | '/_authenticated/admin'
    | '/article/$slug'
    | '/section/$slug'
    | '/api/public/cron/ingest-breaking'
    | '/api/public/cron/ingest-news'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SearchRoute: typeof SearchRoute
  ArticleSlugRoute: typeof ArticleSlugRoute
  SectionSlugRoute: typeof SectionSlugRoute
  ApiPublicCronIngestBreakingRoute: typeof ApiPublicCronIngestBreakingRoute
  ApiPublicCronIngestNewsRoute: typeof ApiPublicCronIngestNewsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$slug': {
      id: '/section/$slug'
      path: '/section/$slug'
      fullPath: '/section/$slug'
      preLoaderRoute: typeof SectionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article/$slug': {
      id: '/article/$slug'
      path: '/article/$slug'
      fullPath: '/article/$slug'
      preLoaderRoute: typeof ArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/ingest-news': {
      id: '/api/public/cron/ingest-news'
      path: '/api/public/cron/ingest-news'
      fullPath: '/api/public/cron/ingest-news'
      preLoaderRoute: typeof ApiPublicCronIngestNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/ingest-breaking': {
      id: '/api/public/cron/ingest-breaking'
      path: '/api/public/cron/ingest-breaking'
      fullPath: '/api/public/cron/ingest-breaking'
      preLoaderRoute: typeof ApiPublicCronIngestBreakingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SearchRoute: SearchRoute,
  ArticleSlugRoute: ArticleSlugRoute,
  SectionSlugRoute: SectionSlugRoute,
  ApiPublicCronIngestBreakingRoute: ApiPublicCronIngestBreakingRoute,
  ApiPublicCronIngestNewsRoute: ApiPublicCronIngestNewsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
